/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;
import classes.Enofilo;
import classes.Compra;
import classes.Produto;
import classes.CartaoPresente;
import classes.Vinho;
import classes.Espumante;
import java.util.ArrayList;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
/**
 *
 * @author Hirya
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal(Enofilo usuario) {
        initComponents();
        this.usuario = usuario;
        this.sPaneCarrinho.setVisible(false);
        this.sPaneEspumante.setVisible(false);
        this.jPaneSobreNos.setVisible(false);
        this.jPaneCartaoPresente.setVisible(false);
        this.jPaneSubMenu.setVisible(false);
        this.sPaneVinho.setVisible(false);
        this.lblDescontoVinho.setVisible(false);
        this.lblDescontoEspumante.setVisible(false);
        this.vinhoT1 = new Vinho(true, false, false, "vinho", "Canário Spätburgunder", 100, 26);
        this.vinhoT2 = new Vinho(true, false, false, "vinho", "Canário Cabernet Sauvignon", 100, 26);
        this.vinhoT3 = new Vinho(true, false, false, "vinho", "Lesnik Classic Cabernet Sauvignon", 50, 87);
        this.vinhoB1 = new Vinho(false, true, false, "vinho", "Canário Gewurztraminer", 100, 23);
        this.vinhoB2 = new Vinho(false, true, false, "vinho", "Canário Riesling", 100, 23);
        this.vinhoB3 = new Vinho(false, true, false, "vinho", "Lesnik Classic Riesling", 50, 79);
        this.espumanteB = new Espumante(false, true, "espumante", "du Dom Brut", 50, 42);
        this.espumanteM = new Espumante(true, false, "espumante", "du Dom Moscatel", 50, 41);
        this.cartao = new CartaoPresente("Cartao","Cartao Presente",0);
        this.carrinho = new ArrayList<Produto>();
        this.notaFiscal = new Compra(carrinho, usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaDaLoja = new javax.swing.JPanel();
        sPaneCarrinho = new javax.swing.JScrollPane();
        jPanel14 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        btnFinalizarCompra = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        lblMensagemFinal = new javax.swing.JLabel();
        lblCarrinho = new javax.swing.JLabel();
        sPaneEspumante = new javax.swing.JScrollPane();
        jPanel11 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        rBtnEspumanteMCarrinho = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        spnEspumanteMCarrinho = new javax.swing.JSpinner();
        rBtnEspumanteBCarrinho = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        spnEspumanteBCarrinho = new javax.swing.JSpinner();
        jPaneSobreNos = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPaneCartaoPresente = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        rBtnCartaoPresenteCarrinho = new javax.swing.JRadioButton();
        spnCartaoPresenteCarrinho = new javax.swing.JSpinner();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnCarrinho = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPaneSubMenu = new javax.swing.JPanel();
        btnVinhos = new javax.swing.JButton();
        btnEspumantes = new javax.swing.JButton();
        btnCartaoPresente = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnSobreNos = new javax.swing.JButton();
        btnProdutos = new javax.swing.JButton();
        sPaneVinho = new javax.swing.JScrollPane();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        spnVinhoT1Carrinho = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rBtnVinhoT1Carrinho = new javax.swing.JRadioButton();
        rBtnVinhoT2Carrinho = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        spnVinhoT2Carrinho = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        rBtnVinhoB1Carrinho = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        spnVinhoB1Carrinho = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        rBtnVinhoB2Carrinho = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        spnVinhoB2Carrinho = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        rBtnVinhoT3Carrinho = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        spnVinhoT3Carrinho = new javax.swing.JSpinner();
        rBtnVinhoB3Carrinho = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        spnVinhoB3Carrinho = new javax.swing.JSpinner();
        jPanel9 = new javax.swing.JPanel();
        lblDescontoVinho = new javax.swing.JLabel();
        lblDescontoEspumante = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 550));
        setMinimumSize(new java.awt.Dimension(1000, 550));
        setPreferredSize(new java.awt.Dimension(1000, 550));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        telaDaLoja.setBackground(new java.awt.Color(153, 0, 0));
        telaDaLoja.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sPaneCarrinho.setBackground(new java.awt.Color(255, 255, 204));

        jPanel14.setBackground(new java.awt.Color(255, 255, 204));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CARRINHO.png"))); // NOI18N
        jPanel14.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, -1, -1));

        btnFinalizarCompra.setBackground(new java.awt.Color(204, 0, 0));
        btnFinalizarCompra.setText("Finalizar compra");
        btnFinalizarCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFinalizarCompraMouseClicked(evt);
            }
        });
        jPanel14.add(btnFinalizarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 11, 117, 54));

        jPanel15.setBackground(new java.awt.Color(153, 0, 0));
        jPanel15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel35.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 204));
        jLabel35.setText("Seu Carrinho de Compras");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 11, -1, -1));

        lblMensagemFinal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMensagemFinal.setText("Compra finalizada com sucesso!!");
        jPanel14.add(lblMensagemFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));
        jPanel14.add(lblCarrinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 370, 228));

        sPaneCarrinho.setViewportView(jPanel14);

        telaDaLoja.add(sPaneCarrinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 540, 400));

        jPanel11.setBackground(new java.awt.Color(255, 255, 204));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tbespumanteB.png"))); // NOI18N

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tbespumanteM.png"))); // NOI18N

        rBtnEspumanteMCarrinho.setText("Para Carrinho");
        rBtnEspumanteMCarrinho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rBtnEspumanteMCarrinhoMouseClicked(evt);
            }
        });

        jLabel26.setText("<html> Vinho Espumante <strong> R$ 41 </strong> <br> du Dom Moscatel</html>");

        jLabel27.setText("Indique a quantidade");

        spnEspumanteMCarrinho.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        spnEspumanteMCarrinho.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnEspumanteMCarrinhoStateChanged(evt);
            }
        });

        rBtnEspumanteBCarrinho.setText("Para Carrinho");
        rBtnEspumanteBCarrinho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rBtnEspumanteBCarrinhoMouseClicked(evt);
            }
        });

        jLabel28.setText("<html> Vinho Espumante <strong> R$ 42 </strong> <br> du Dom Brut </html>");

        jLabel29.setText("Indique a quantidade");

        spnEspumanteBCarrinho.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        spnEspumanteBCarrinho.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnEspumanteBCarrinhoStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel24)
                        .addComponent(rBtnEspumanteBCarrinho))
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnEspumanteBCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(111, 111, 111)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnEspumanteMCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rBtnEspumanteMCarrinho)
                    .addComponent(jLabel25))
                .addContainerGap(335, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rBtnEspumanteMCarrinho)
                    .addComponent(rBtnEspumanteBCarrinho))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel24))
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(spnEspumanteBCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(spnEspumanteMCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        sPaneEspumante.setViewportView(jPanel11);

        telaDaLoja.add(sPaneEspumante, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 540, 400));

        jPaneSobreNos.setBackground(new java.awt.Color(255, 255, 204));

        jLabel33.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(153, 0, 0));
        jLabel33.setText("História da Vinícola Lesnik");

        jLabel34.setText("<html>A vinícola Lesnik foi erguida pelo sonho da CEO e fundadora Janisy Lesnik, em 1990, na cidade<br> de Dom Feliciano, Rio Grande do Sul. Inspirada pela tradição da família,  se esforçou como a <br>  primeira empreendedora  mulher na região no setor vitivinícola.</html>");

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/familiavinicola.jpg"))); // NOI18N

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ccovinicola.jpg"))); // NOI18N

        javax.swing.GroupLayout jPaneSobreNosLayout = new javax.swing.GroupLayout(jPaneSobreNos);
        jPaneSobreNos.setLayout(jPaneSobreNosLayout);
        jPaneSobreNosLayout.setHorizontalGroup(
            jPaneSobreNosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneSobreNosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPaneSobreNosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneSobreNosLayout.createSequentialGroup()
                        .addGroup(jPaneSobreNosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPaneSobreNosLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel36))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPaneSobreNosLayout.setVerticalGroup(
            jPaneSobreNosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneSobreNosLayout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addGroup(jPaneSobreNosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneSobreNosLayout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jLabel36)
                .addContainerGap())
        );

        telaDaLoja.add(jPaneSobreNos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 540, 400));

        jLabel30.setText("Cartão Presente");

        rBtnCartaoPresenteCarrinho.setText("Para Carrinho");
        rBtnCartaoPresenteCarrinho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rBtnCartaoPresenteCarrinhoMouseClicked(evt);
            }
        });

        spnCartaoPresenteCarrinho.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 1));
        spnCartaoPresenteCarrinho.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnCartaoPresenteCarrinhoStateChanged(evt);
            }
        });

        jLabel31.setText("Indique o valor que deseja enviar de presente  (R$)");

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cartão presente.png"))); // NOI18N

        javax.swing.GroupLayout jPaneCartaoPresenteLayout = new javax.swing.GroupLayout(jPaneCartaoPresente);
        jPaneCartaoPresente.setLayout(jPaneCartaoPresenteLayout);
        jPaneCartaoPresenteLayout.setHorizontalGroup(
            jPaneCartaoPresenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneCartaoPresenteLayout.createSequentialGroup()
                .addGroup(jPaneCartaoPresenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneCartaoPresenteLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPaneCartaoPresenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPaneCartaoPresenteLayout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addGap(18, 18, 18)
                                .addComponent(spnCartaoPresenteCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rBtnCartaoPresenteCarrinho)
                            .addComponent(jLabel30)))
                    .addGroup(jPaneCartaoPresenteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPaneCartaoPresenteLayout.setVerticalGroup(
            jPaneCartaoPresenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneCartaoPresenteLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(rBtnCartaoPresenteCarrinho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPaneCartaoPresenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnCartaoPresenteCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addGap(25, 25, 25))
        );

        telaDaLoja.add(jPaneCartaoPresente, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 540, 400));

        jPanel3.setBackground(new java.awt.Color(153, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Gabriola", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("<html><strong>Lesnik Winery</strong>   \"O Melhor Vinho de Dom Feliciano ! \" </html>");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, -20, -1, 90));

        btnCarrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CARRINHO.png"))); // NOI18N
        btnCarrinho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCarrinhoMouseClicked(evt);
            }
        });
        jPanel3.add(btnCarrinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, -10, 110, -1));

        telaDaLoja.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 980, 70));

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        telaDaLoja.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 280, 10));

        jPaneSubMenu.setBackground(new java.awt.Color(153, 0, 0));

        btnVinhos.setText("Vinhos");
        btnVinhos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVinhosMouseClicked(evt);
            }
        });

        btnEspumantes.setText("Espumantes");
        btnEspumantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEspumantesMouseClicked(evt);
            }
        });

        btnCartaoPresente.setText("Cartão Presente");
        btnCartaoPresente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCartaoPresenteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPaneSubMenuLayout = new javax.swing.GroupLayout(jPaneSubMenu);
        jPaneSubMenu.setLayout(jPaneSubMenuLayout);
        jPaneSubMenuLayout.setHorizontalGroup(
            jPaneSubMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneSubMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPaneSubMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnVinhos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCartaoPresente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEspumantes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPaneSubMenuLayout.setVerticalGroup(
            jPaneSubMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneSubMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVinhos)
                .addGap(18, 18, 18)
                .addComponent(btnEspumantes)
                .addGap(18, 18, 18)
                .addComponent(btnCartaoPresente)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        telaDaLoja.add(jPaneSubMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 130, 140));

        jPanel4.setBackground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        telaDaLoja.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 440));

        jPanel5.setBackground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        telaDaLoja.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 30, 290));

        jPanel7.setBackground(new java.awt.Color(153, 0, 0));

        btnSobreNos.setText("Nossa História");
        btnSobreNos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSobreNosMouseClicked(evt);
            }
        });

        btnProdutos.setText("Produtos");
        btnProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProdutosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSobreNos, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1016, 1016, 1016))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btnSobreNos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        telaDaLoja.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 180, 250));

        jPanel10.setBackground(new java.awt.Color(204, 219, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tbvinhot1.png"))); // NOI18N

        jLabel5.setText("<html>Vinho Tinto Fino<strong> R$26</strong<br> Canário Spätburgunder<br> </html>");

        spnVinhoT1Carrinho.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnVinhoT1CarrinhoStateChanged(evt);
            }
        });

        jLabel6.setText("Indique a quantidade");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tbvinhot2.png"))); // NOI18N

        rBtnVinhoT1Carrinho.setText("Para Carrinho");
        rBtnVinhoT1Carrinho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rBtnVinhoT1CarrinhoMouseClicked(evt);
            }
        });

        rBtnVinhoT2Carrinho.setText("Para Carrinho");
        rBtnVinhoT2Carrinho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rBtnVinhoT2CarrinhoMouseClicked(evt);
            }
        });

        jLabel8.setText("<html> Vinho Tinto Fino <strong> R$ 26 </strong> <br> Canário Cabernet Sauvignon</html>");

        jLabel9.setText("Indique a quantidade");

        spnVinhoT2Carrinho.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnVinhoT2CarrinhoStateChanged(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tbvinhob1.png"))); // NOI18N

        rBtnVinhoB1Carrinho.setText("Para Carrinho");
        rBtnVinhoB1Carrinho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rBtnVinhoB1CarrinhoMouseClicked(evt);
            }
        });

        jLabel11.setText("<html>Vinho Branco Fino <strong>R$23</strong><br>Canário Gewurztraminer </html>");

        jLabel12.setText("Indique a quantidade");

        spnVinhoB1Carrinho.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnVinhoB1CarrinhoStateChanged(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tbvinhob2.png"))); // NOI18N

        rBtnVinhoB2Carrinho.setText("Para Carrinho");
        rBtnVinhoB2Carrinho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rBtnVinhoB2CarrinhoMouseClicked(evt);
            }
        });

        jLabel14.setText("<html>Vinho Branco Fino <strong>R$23</strong><br>Canário Riesling </html>");

        jLabel15.setText("Indique a quantidade");

        spnVinhoB2Carrinho.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnVinhoB2CarrinhoStateChanged(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tbvinhoTcarvalho.png"))); // NOI18N

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tbvinhoBcarvalho.png"))); // NOI18N

        rBtnVinhoT3Carrinho.setText("Para Carrinho");
        rBtnVinhoT3Carrinho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rBtnVinhoT3CarrinhoMouseClicked(evt);
            }
        });

        jLabel18.setText("<html>Vinho Tinto Fino <strong>R$87</strong><br>Lesnik Classic<br> Cabernet Sauvignon</html>");

        jLabel19.setText("Indique a quantidade");

        spnVinhoT3Carrinho.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnVinhoT3CarrinhoStateChanged(evt);
            }
        });

        rBtnVinhoB3Carrinho.setText("Para Carrinho");
        rBtnVinhoB3Carrinho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rBtnVinhoB3CarrinhoMouseClicked(evt);
            }
        });

        jLabel20.setText("<html>Vinho Branco Fino <strong>R$79</strong><br>Lesnik Classic Riesling</html>");

        jLabel21.setText("Indique a quantidade");

        spnVinhoB3Carrinho.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnVinhoB3CarrinhoStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel4))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnVinhoT1Carrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rBtnVinhoT1Carrinho)
                    .addComponent(rBtnVinhoB1Carrinho)
                    .addComponent(jLabel10)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnVinhoB1Carrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel16))
                    .addComponent(rBtnVinhoT3Carrinho)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnVinhoT3Carrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnVinhoB3Carrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rBtnVinhoT2Carrinho)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnVinhoT2Carrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(rBtnVinhoB2Carrinho)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnVinhoB2Carrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(rBtnVinhoB3Carrinho))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rBtnVinhoT1Carrinho)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rBtnVinhoT2Carrinho)))
                .addGap(73, 73, 73)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(spnVinhoT1Carrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(spnVinhoT2Carrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(rBtnVinhoB1Carrinho))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(rBtnVinhoB2Carrinho)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(spnVinhoB2Carrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(spnVinhoB1Carrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(rBtnVinhoT3Carrinho))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rBtnVinhoB3Carrinho)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(spnVinhoB3Carrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(spnVinhoT3Carrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(384, Short.MAX_VALUE))
        );

        sPaneVinho.setViewportView(jPanel10);

        telaDaLoja.add(sPaneVinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 540, 400));

        jPanel9.setBackground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        telaDaLoja.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 80, 60, 420));

        lblDescontoVinho.setBackground(new java.awt.Color(255, 204, 204));
        lblDescontoVinho.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDescontoVinho.setText("compra de caixa de 6un ganha 5% desconto");
        telaDaLoja.add(lblDescontoVinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, -1, -1));

        lblDescontoEspumante.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDescontoEspumante.setText("compra de caixa com 6un ganha 12% desconto");
        telaDaLoja.add(lblDescontoEspumante, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, -1, -1));

        jLabel2.setFont(new java.awt.Font("Gabriola", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("<html><strong>Lesnik Winery</strong> - Cadastro </html>");
        telaDaLoja.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, -20, -1, 90));

        jPanel6.setBackground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        telaDaLoja.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 230, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/canariob1.jpg"))); // NOI18N
        jLabel1.setText(" ");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        telaDaLoja.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1020, -1));

        getContentPane().add(telaDaLoja, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSobreNosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSobreNosMouseClicked
        // TODO add your handling code here:
        this.jPaneSobreNos.setVisible(!this.jPaneSobreNos.isVisible());
        this.sPaneCarrinho.setVisible(false);
        this.sPaneEspumante.setVisible(false);
        this.jPaneCartaoPresente.setVisible(false);
        this.jPaneSubMenu.setVisible(false);
        this.sPaneVinho.setVisible(false);
        this.lblDescontoVinho.setVisible(false);
        this.lblDescontoEspumante.setVisible(false);
    }//GEN-LAST:event_btnSobreNosMouseClicked

    private void btnProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdutosMouseClicked
        // TODO add your handling code here:
        this.sPaneCarrinho.setVisible(false);
        this.sPaneEspumante.setVisible(false);
        this.jPaneSobreNos.setVisible(false);
        this.jPaneCartaoPresente.setVisible(false);
        this.jPaneSubMenu.setVisible(!this.jPaneSubMenu.isVisible());
        this.sPaneVinho.setVisible(false);
        this.lblDescontoVinho.setVisible(false);
        this.lblDescontoEspumante.setVisible(false);
    }//GEN-LAST:event_btnProdutosMouseClicked

    private void btnVinhosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVinhosMouseClicked
        // TODO add your handling code here:
        this.sPaneCarrinho.setVisible(false);
        this.sPaneEspumante.setVisible(false);
        this.jPaneSobreNos.setVisible(false);
        this.jPaneCartaoPresente.setVisible(false);
        this.sPaneVinho.setVisible(!this.sPaneVinho.isVisible());
        this.lblDescontoVinho.setVisible(!this.lblDescontoVinho.isVisible());
        this.lblDescontoEspumante.setVisible(false);
    }//GEN-LAST:event_btnVinhosMouseClicked

    private void btnEspumantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEspumantesMouseClicked
        // TODO add your handling code here:
        this.sPaneCarrinho.setVisible(false);
        this.sPaneEspumante.setVisible(!this.sPaneEspumante.isVisible());
        this.jPaneSobreNos.setVisible(false);
        this.jPaneCartaoPresente.setVisible(false);
        this.sPaneVinho.setVisible(false);
        this.lblDescontoVinho.setVisible(false);
        this.lblDescontoEspumante.setVisible(!this.lblDescontoEspumante.isVisible());
    }//GEN-LAST:event_btnEspumantesMouseClicked

    private void btnCartaoPresenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCartaoPresenteMouseClicked
        // TODO add your handling code here:
        this.sPaneCarrinho.setVisible(false);
        this.sPaneEspumante.setVisible(false);
        this.jPaneSobreNos.setVisible(false);
        this.jPaneCartaoPresente.setVisible(!this.jPaneCartaoPresente.isVisible());
        this.sPaneVinho.setVisible(false);
        this.lblDescontoVinho.setVisible(false);
        this.lblDescontoEspumante.setVisible(false);
    }//GEN-LAST:event_btnCartaoPresenteMouseClicked

    private void btnCarrinhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarrinhoMouseClicked
        // TODO add your handling code here:
        this.sPaneCarrinho.setVisible(!this.sPaneCarrinho.isVisible());
        this.sPaneEspumante.setVisible(false);
        this.jPaneSobreNos.setVisible(false);
        this.jPaneCartaoPresente.setVisible(false);
        this.jPaneSubMenu.setVisible(false);
        this.sPaneVinho.setVisible(false);
        this.lblDescontoVinho.setVisible(false);
        this.lblDescontoEspumante.setVisible(false);
        this.lblMensagemFinal.setVisible(false);
        if(carrinho.isEmpty())
        {
            this.lblCarrinho.setText("<html><strong>Carrinho Vazio !</strong></html>");
        }
        else
        {
            notaFiscal.gerarValorTotal(carrinho);
            String lista = "<ul>";
            for(Produto item : carrinho)
            {
                lista = lista.concat("<li>" + "(" + item.getTipo() + ") " + item.getNome() + " x" + item.getQuantidadeCarrinho() + "</li>");
            }
            lista = lista.concat("</ul>");
            this.lblCarrinho.setText("<html><strong>Consumidor: </strong>" + usuario.getNomeCompleto() + "<br><strong>Produtos:</strong><br>" + lista + "<br><strong>Valor Total: R$ </strong>" + notaFiscal.getValorTotal()+ "<br><strong>Desconto Total: R$ </strong>" + notaFiscal.getValorDescontoTotal() + "<br><strong>Valor Total Final: R$ </strong>" + notaFiscal.getValorTotalFinal() + "</html>");
        }
    }//GEN-LAST:event_btnCarrinhoMouseClicked

    private void rBtnEspumanteBCarrinhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rBtnEspumanteBCarrinhoMouseClicked
        // TODO add your handling code here:
        if(this.rBtnEspumanteBCarrinho.isSelected())
        {
            if((int)this.spnEspumanteBCarrinho.getValue() > 0)
            {
                carrinho.add(espumanteB);
                this.rBtnEspumanteBCarrinho.setSelected(true);
            }
            else
            {
                this.rBtnEspumanteBCarrinho.setSelected(false);
            }
        }
        else
        {
            espumanteB.setQuantidadeCarrinho(0); 
            espumanteB.setQuantidadeEstoque(50);
            SpinnerModel model = new SpinnerNumberModel(espumanteB.getQuantidadeCarrinho(), 0, espumanteB.getQuantidadeEstoque(), 1); //default value,lower bound,upper bound,increment by
            this.spnEspumanteBCarrinho.setModel(model);
            carrinho.remove(espumanteB);
            this.rBtnEspumanteBCarrinho.setSelected(false);
        }
    }//GEN-LAST:event_rBtnEspumanteBCarrinhoMouseClicked

    private void spnEspumanteBCarrinhoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnEspumanteBCarrinhoStateChanged
        // TODO add your handling code here:
        espumanteB.setQuantidadeCarrinho((int)this.spnEspumanteBCarrinho.getValue()); 
        espumanteB.alterarEstoque((int)this.spnEspumanteBCarrinho.getValue());
        SpinnerModel model = new SpinnerNumberModel(espumanteB.getQuantidadeCarrinho(), 0, espumanteB.getQuantidadeEstoque(), 1); //default value,lower bound,upper bound,increment by
        this.spnEspumanteBCarrinho.setModel(model);
    }//GEN-LAST:event_spnEspumanteBCarrinhoStateChanged

    private void spnEspumanteMCarrinhoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnEspumanteMCarrinhoStateChanged
        // TODO add your handling code here:
        espumanteM.setQuantidadeCarrinho((int)this.spnEspumanteMCarrinho.getValue()); 
        espumanteM.alterarEstoque((int)this.spnEspumanteMCarrinho.getValue());
        SpinnerModel model = new SpinnerNumberModel(espumanteM.getQuantidadeCarrinho(), 0, espumanteM.getQuantidadeEstoque(), 1); //default value,lower bound,upper bound,increment by
        this.spnEspumanteMCarrinho.setModel(model);
    }//GEN-LAST:event_spnEspumanteMCarrinhoStateChanged

    private void rBtnEspumanteMCarrinhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rBtnEspumanteMCarrinhoMouseClicked
        // TODO add your handling code here:
        if(this.rBtnEspumanteMCarrinho.isSelected())
        {
            if((int)this.spnEspumanteMCarrinho.getValue() > 0)
            {
                carrinho.add(espumanteM);
                this.rBtnEspumanteMCarrinho.setSelected(true);
            }
            else
            {
                this.rBtnEspumanteMCarrinho.setSelected(false);
            }
        }
        else
        {
            espumanteM.setQuantidadeCarrinho(0);
            espumanteM.setQuantidadeEstoque(50);
            SpinnerModel model = new SpinnerNumberModel(espumanteM.getQuantidadeCarrinho(), 0, espumanteM.getQuantidadeEstoque(), 1); //default value,lower bound,upper bound,increment by
            this.spnEspumanteMCarrinho.setModel(model);
            carrinho.remove(espumanteM);
            this.rBtnEspumanteMCarrinho.setSelected(false);
        }
    }//GEN-LAST:event_rBtnEspumanteMCarrinhoMouseClicked

    private void rBtnVinhoT1CarrinhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rBtnVinhoT1CarrinhoMouseClicked
        // TODO add your handling code here:
        if(this.rBtnVinhoT1Carrinho.isSelected())
        {
            if((int)this.spnVinhoT1Carrinho.getValue() > 0)
            {
                carrinho.add(vinhoT1);
                this.rBtnVinhoT1Carrinho.setSelected(true);
            }
            else
            {
                this.rBtnVinhoT1Carrinho.setSelected(false);
            }
        }
        else
        {
            vinhoT1.setQuantidadeCarrinho(0);
            vinhoT1.setQuantidadeEstoque(100);
            SpinnerModel model = new SpinnerNumberModel(vinhoT1.getQuantidadeCarrinho(), 0, vinhoT1.getQuantidadeEstoque(), 1); //default value,lower bound,upper bound,increment by
            this.spnVinhoT1Carrinho.setModel(model);
            carrinho.remove(vinhoT1);
            this.rBtnVinhoT1Carrinho.setSelected(false);
        }
    }//GEN-LAST:event_rBtnVinhoT1CarrinhoMouseClicked

    private void spnVinhoT1CarrinhoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnVinhoT1CarrinhoStateChanged
        // TODO add your handling code here:
        vinhoT1.setQuantidadeCarrinho((int)this.spnVinhoT1Carrinho.getValue()); 
        vinhoT1.alterarEstoque((int)this.spnVinhoT1Carrinho.getValue());
        SpinnerModel model = new SpinnerNumberModel(vinhoT1.getQuantidadeCarrinho(), 0, vinhoT1.getQuantidadeEstoque(), 1); //default value,lower bound,upper bound,increment by
        this.spnVinhoT1Carrinho.setModel(model);
    }//GEN-LAST:event_spnVinhoT1CarrinhoStateChanged

    private void rBtnVinhoT2CarrinhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rBtnVinhoT2CarrinhoMouseClicked
        // TODO add your handling code here:
        if(this.rBtnVinhoT2Carrinho.isSelected())
        {
            if((int)this.spnVinhoT2Carrinho.getValue() > 0)
            {
                carrinho.add(vinhoT2);
                this.rBtnVinhoT2Carrinho.setSelected(true);
            }
            else
            {
                this.rBtnVinhoT2Carrinho.setSelected(false);
            }
        }
        else
        {
            vinhoT2.setQuantidadeCarrinho(0);
            vinhoT2.setQuantidadeEstoque(100);
            SpinnerModel model = new SpinnerNumberModel(vinhoT2.getQuantidadeCarrinho(), 0, vinhoT2.getQuantidadeEstoque(), 1); //default value,lower bound,upper bound,increment by
            this.spnVinhoT2Carrinho.setModel(model);
            carrinho.remove(vinhoT2);
            this.rBtnVinhoT2Carrinho.setSelected(false);
        }
    }//GEN-LAST:event_rBtnVinhoT2CarrinhoMouseClicked

    private void spnVinhoT2CarrinhoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnVinhoT2CarrinhoStateChanged
        // TODO add your handling code here:
        vinhoT2.setQuantidadeCarrinho((int)this.spnVinhoT2Carrinho.getValue()); 
        vinhoT2.alterarEstoque((int)this.spnVinhoT2Carrinho.getValue());
        SpinnerModel model = new SpinnerNumberModel(vinhoT2.getQuantidadeCarrinho(), 0, vinhoT2.getQuantidadeEstoque(), 1); //default value,lower bound,upper bound,increment by
        this.spnVinhoT2Carrinho.setModel(model);
    }//GEN-LAST:event_spnVinhoT2CarrinhoStateChanged

    private void rBtnVinhoT3CarrinhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rBtnVinhoT3CarrinhoMouseClicked
        // TODO add your handling code here:
        if(this.rBtnVinhoT3Carrinho.isSelected())
        {
            if((int)this.spnVinhoT3Carrinho.getValue() > 0)
            {
                carrinho.add(vinhoT3);
                this.rBtnVinhoT3Carrinho.setSelected(true);
            }
            else
            {
                this.rBtnVinhoT3Carrinho.setSelected(false);
            }
        }
        else
        {
            vinhoT3.setQuantidadeCarrinho(0);
            vinhoT3.setQuantidadeEstoque(50);
            SpinnerModel model = new SpinnerNumberModel(vinhoT3.getQuantidadeCarrinho(), 0, vinhoT3.getQuantidadeEstoque(), 1); //default value,lower bound,upper bound,increment by
            this.spnVinhoT3Carrinho.setModel(model);
            carrinho.remove(vinhoT3);
            this.rBtnVinhoT3Carrinho.setSelected(false);
        }
    }//GEN-LAST:event_rBtnVinhoT3CarrinhoMouseClicked

    private void spnVinhoT3CarrinhoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnVinhoT3CarrinhoStateChanged
        // TODO add your handling code here:
        vinhoT3.setQuantidadeCarrinho((int)this.spnVinhoT3Carrinho.getValue()); 
        vinhoT3.alterarEstoque((int)this.spnVinhoT3Carrinho.getValue());
        SpinnerModel model = new SpinnerNumberModel(vinhoT3.getQuantidadeCarrinho(), 0, vinhoT3.getQuantidadeEstoque(), 1); //default value,lower bound,upper bound,increment by
        this.spnVinhoT3Carrinho.setModel(model);
    }//GEN-LAST:event_spnVinhoT3CarrinhoStateChanged

    private void rBtnVinhoB1CarrinhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rBtnVinhoB1CarrinhoMouseClicked
        // TODO add your handling code here:
        if(this.rBtnVinhoB1Carrinho.isSelected())
        {
            if((int)this.spnVinhoB1Carrinho.getValue() > 0)
            {
                carrinho.add(vinhoB1);
                this.rBtnVinhoB1Carrinho.setSelected(true);
            }
            else
            {
                this.rBtnVinhoB1Carrinho.setSelected(false);
            }
        }
        else
        {
            vinhoB1.setQuantidadeCarrinho(0);
            vinhoB1.setQuantidadeEstoque(100);
            SpinnerModel model = new SpinnerNumberModel(vinhoB1.getQuantidadeCarrinho(), 0, vinhoB1.getQuantidadeEstoque(), 1); //default value,lower bound,upper bound,increment by
            this.spnVinhoB1Carrinho.setModel(model);
            carrinho.remove(vinhoB1);
            this.rBtnVinhoB1Carrinho.setSelected(false);
        }
    }//GEN-LAST:event_rBtnVinhoB1CarrinhoMouseClicked

    private void spnVinhoB1CarrinhoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnVinhoB1CarrinhoStateChanged
        // TODO add your handling code here:
        vinhoB1.setQuantidadeCarrinho((int)this.spnVinhoB1Carrinho.getValue()); 
        vinhoB1.alterarEstoque((int)this.spnVinhoB1Carrinho.getValue());
        SpinnerModel model = new SpinnerNumberModel(vinhoB1.getQuantidadeCarrinho(), 0, vinhoB1.getQuantidadeEstoque(), 1); //default value,lower bound,upper bound,increment by
        this.spnVinhoB1Carrinho.setModel(model);
    }//GEN-LAST:event_spnVinhoB1CarrinhoStateChanged

    private void rBtnVinhoB2CarrinhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rBtnVinhoB2CarrinhoMouseClicked
        // TODO add your handling code here:
        if(this.rBtnVinhoB2Carrinho.isSelected())
        {
            if((int)this.spnVinhoB2Carrinho.getValue() > 0)
            {
                carrinho.add(vinhoB2);
                this.rBtnVinhoB2Carrinho.setSelected(true);
            }
            else
            {
                this.rBtnVinhoB2Carrinho.setSelected(false);
            }
        }
        else
        {
            vinhoB2.setQuantidadeCarrinho(0);
            vinhoB2.setQuantidadeEstoque(100);
            SpinnerModel model = new SpinnerNumberModel(vinhoB2.getQuantidadeCarrinho(), 0, vinhoB2.getQuantidadeEstoque(), 1); //default value,lower bound,upper bound,increment by
            this.spnVinhoB2Carrinho.setModel(model);
            carrinho.remove(vinhoB2);
            this.rBtnVinhoB2Carrinho.setSelected(false);
        }
    }//GEN-LAST:event_rBtnVinhoB2CarrinhoMouseClicked

    private void spnVinhoB2CarrinhoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnVinhoB2CarrinhoStateChanged
        // TODO add your handling code here:
        vinhoB2.setQuantidadeCarrinho((int)this.spnVinhoB2Carrinho.getValue()); 
        vinhoB2.alterarEstoque((int)this.spnVinhoB2Carrinho.getValue());
        SpinnerModel model = new SpinnerNumberModel(vinhoB2.getQuantidadeCarrinho(), 0, vinhoB2.getQuantidadeEstoque(), 1); //default value,lower bound,upper bound,increment by
        this.spnVinhoB2Carrinho.setModel(model);
    }//GEN-LAST:event_spnVinhoB2CarrinhoStateChanged

    private void rBtnVinhoB3CarrinhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rBtnVinhoB3CarrinhoMouseClicked
        // TODO add your handling code here:
        if(this.rBtnVinhoB3Carrinho.isSelected())
        {
            if((int)this.spnVinhoB3Carrinho.getValue() > 0)
            {
                carrinho.add(vinhoB3);
                this.rBtnVinhoB3Carrinho.setSelected(true);
            }
            else
            {
                this.rBtnVinhoB3Carrinho.setSelected(false);
            }
        }
        else
        {
            vinhoB3.setQuantidadeCarrinho(0);
            vinhoB3.setQuantidadeEstoque(50);
            SpinnerModel model = new SpinnerNumberModel(vinhoB3.getQuantidadeCarrinho(), 0, vinhoB3.getQuantidadeEstoque(), 1); //default value,lower bound,upper bound,increment by
            this.spnVinhoB3Carrinho.setModel(model);
            carrinho.remove(vinhoB3);
            this.rBtnVinhoB3Carrinho.setSelected(false);
        }
    }//GEN-LAST:event_rBtnVinhoB3CarrinhoMouseClicked

    private void spnVinhoB3CarrinhoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnVinhoB3CarrinhoStateChanged
        // TODO add your handling code here:
        vinhoB3.setQuantidadeCarrinho((int)this.spnVinhoB3Carrinho.getValue()); 
        vinhoB3.alterarEstoque((int)this.spnVinhoB3Carrinho.getValue());
        SpinnerModel model = new SpinnerNumberModel(vinhoB3.getQuantidadeCarrinho(), 0, vinhoB3.getQuantidadeEstoque(), 1); //default value,lower bound,upper bound,increment by
        this.spnVinhoB3Carrinho.setModel(model);
    }//GEN-LAST:event_spnVinhoB3CarrinhoStateChanged

    private void rBtnCartaoPresenteCarrinhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rBtnCartaoPresenteCarrinhoMouseClicked
        // TODO add your handling code here:
        if(this.rBtnCartaoPresenteCarrinho.isSelected())
        {
            if((int)this.spnCartaoPresenteCarrinho.getValue() > 0)
            {
                carrinho.add(cartao);
                this.rBtnCartaoPresenteCarrinho.setSelected(true);
            }
            else
            {
                this.rBtnCartaoPresenteCarrinho.setSelected(false);
            }
        }
        else
        {
            carrinho.remove(cartao);
        }
    }//GEN-LAST:event_rBtnCartaoPresenteCarrinhoMouseClicked

    private void spnCartaoPresenteCarrinhoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnCartaoPresenteCarrinhoStateChanged
        // TODO add your handling code here:
        cartao.setQuantidadeCarrinho((int)this.spnCartaoPresenteCarrinho.getValue()); 
    }//GEN-LAST:event_spnCartaoPresenteCarrinhoStateChanged

    private void btnFinalizarCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinalizarCompraMouseClicked
        // TODO add your handling code here:
        if(carrinho.isEmpty())
        {
            
        }
        else
        {
            this.lblCarrinho.setVisible(false);
            this.lblMensagemFinal.setVisible(true);
        }
    }//GEN-LAST:event_btnFinalizarCompraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }
    private CartaoPresente cartao;
    private Vinho vinhoT1;
    private Vinho vinhoT2;
    private Vinho vinhoT3;
    private Vinho vinhoB1;
    private Vinho vinhoB2;
    private Vinho vinhoB3;
    private Espumante espumanteB;
    private Espumante espumanteM;
    private ArrayList<Produto> carrinho;
    private Compra notaFiscal;
    private Enofilo usuario;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarrinho;
    private javax.swing.JButton btnCartaoPresente;
    private javax.swing.JButton btnEspumantes;
    private javax.swing.JButton btnFinalizarCompra;
    private javax.swing.JButton btnProdutos;
    private javax.swing.JButton btnSobreNos;
    private javax.swing.JButton btnVinhos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPaneCartaoPresente;
    private javax.swing.JPanel jPaneSobreNos;
    private javax.swing.JPanel jPaneSubMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblCarrinho;
    private javax.swing.JLabel lblDescontoEspumante;
    private javax.swing.JLabel lblDescontoVinho;
    private javax.swing.JLabel lblMensagemFinal;
    private javax.swing.JRadioButton rBtnCartaoPresenteCarrinho;
    private javax.swing.JRadioButton rBtnEspumanteBCarrinho;
    private javax.swing.JRadioButton rBtnEspumanteMCarrinho;
    private javax.swing.JRadioButton rBtnVinhoB1Carrinho;
    private javax.swing.JRadioButton rBtnVinhoB2Carrinho;
    private javax.swing.JRadioButton rBtnVinhoB3Carrinho;
    private javax.swing.JRadioButton rBtnVinhoT1Carrinho;
    private javax.swing.JRadioButton rBtnVinhoT2Carrinho;
    private javax.swing.JRadioButton rBtnVinhoT3Carrinho;
    private javax.swing.JScrollPane sPaneCarrinho;
    private javax.swing.JScrollPane sPaneEspumante;
    private javax.swing.JScrollPane sPaneVinho;
    private javax.swing.JSpinner spnCartaoPresenteCarrinho;
    private javax.swing.JSpinner spnEspumanteBCarrinho;
    private javax.swing.JSpinner spnEspumanteMCarrinho;
    private javax.swing.JSpinner spnVinhoB1Carrinho;
    private javax.swing.JSpinner spnVinhoB2Carrinho;
    private javax.swing.JSpinner spnVinhoB3Carrinho;
    private javax.swing.JSpinner spnVinhoT1Carrinho;
    private javax.swing.JSpinner spnVinhoT2Carrinho;
    private javax.swing.JSpinner spnVinhoT3Carrinho;
    private javax.swing.JPanel telaDaLoja;
    // End of variables declaration//GEN-END:variables
}
